"""Merge every builder's output into src/data.js (embedded in the app) and data/out/data.json (the daily update the app downloads).
Players who drop out of a feed mid-season are KEPT (availability 0) so saved squads and Clash games never point at a missing player."""
import json, datetime, os
from pathlib import Path
D = Path(__file__).parent
data = json.load(open(D / 'all.json')); data['srp'] = json.load(open(D / 'sr.json')); data['tst'] = json.load(open(D / 'tst.json'))
for lid in ('prem', 'urc'):
    c = json.load(open(D / (lid + '.json'))); data[lid] = {k: c[k] for k in ('fields', 'players', 'games', 'roundDates', 'table', 'source')}
X = json.load(open(D / 'extra.json'))
for lid, t in X['tables'].items(): data[lid]['table'] = t
data['epl']['games'] = X['epl']['games']; data['epl']['roundDates'] = X['epl']['roundDates']; data['epl']['live'] = X['epl']['live']
data['epl']['source'] += '; real fixtures, deadlines and finished-GW points from the FPL API'
# keep players who vanished from a feed (saved teams must still resolve) — previous published file, if any
prev_f = Path(os.environ.get('C7_PREV', D / 'out' / 'data.json'))
kept = 0
if prev_f.exists():
    try:
        prev = json.load(open(prev_f))['data']
        for lid, d in data.items():
            if lid not in prev: continue
            f = d['fields'].split(); pf = prev[lid]['fields'].split(); ai = f.index('av')
            have = {(r[0], r[1]) for r in d['players']}; names = {r[0] for r in d['players']}
            for r in prev[lid]['players']:
                if r[0] in names: continue                      # same player, new club → already present
                row = [r[pf.index(k)] if k in pf else None for k in f]; row[ai] = 0; d['players'].append(row); d.setdefault('gone', []).append(r[0]); kept += 1
    except Exception as e: print('prev merge skipped:', e)
built = datetime.datetime.utcnow().replace(microsecond=0).isoformat() + 'Z'
js = ('/* AUTO-GENERATED by data/merge.py (see README: data pipeline). Do not hand-edit. */\n'
      f"var DATA_V = '{built}', DATA_SRC = 'built-in';\n"
      'var DATA = ' + json.dumps(data, ensure_ascii=False, separators=(',', ':')) + ';\n'
      "(function () { try { const s = localStorage.getItem('code7_data'); if (!s) return; const o = JSON.parse(s); if (!(o && o.v > DATA_V && o.data && o.data.nba && o.data.tst)) return;\n"
      "  for (const lid in DATA) { const u = o.data[lid]; if (!u) { o.data[lid] = DATA[lid]; continue; } const f = u.fields.split(' '), bf = DATA[lid].fields.split(' '), ai = f.indexOf('av'); const have = new Set(u.players.map(r => r[0]));\n"
      "    DATA[lid].players.forEach(r => { if (!have.has(r[0])) { const row = f.map(k => { const i = bf.indexOf(k); return i < 0 ? null : r[i]; }); row[ai] = 0; u.players.push(row); (u.gone = u.gone || []).push(r[0]); } }); }   // never lose a player a saved team uses (hidden from selection)\n"
      "  DATA = o.data; DATA_V = o.v; DATA_SRC = 'update'; } catch (e) { } })();\n")
open(D.parent / 'src' / 'data.js', 'w').write(js)
(D / 'out').mkdir(exist_ok=True)
json.dump({'v': built, 'data': data}, open(D / 'out' / 'data.json', 'w'), ensure_ascii=False, separators=(',', ':'))
print('src/data.js + data/out/data.json', built, len(js), {k: len(v['players']) for k, v in data.items()}, 'kept', kept)
